config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    resources :orderlists
    patch 'complete_order'
  end
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :orderlists
	has_many :pizza, through: :orderlists 
end

app/models/orderlist.rb
class Orderlist < ApplicationRecord
  belongs_to :pizza
  belongs_to :order

  validates :size, presence: true

  before_save :multipler

  enum size: { small: 1, medium: 2, large: 3 }

  after_save :refresh_order

  def multipler
    if (self.size == 'large')
      self.price = self.pizza.price * 3
    elsif  (self.size == 'medium')
      self.price = self.pizza.price * 2
    else
      self.price = self.pizza.price
    end   
      puts 'inside multipler'
  end

  def refresh_order
    self.order.refresh
  end
end
  

app/models/pizza.rb
class Pizza < ApplicationRecord
	has_many :orderlists
	has_many :orders, through: :orderlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @Pizzas = Pizza.all
  end
end

app/controllers/orderlists_controller.rb
class OrderlistsController < ApplicationController
  before_action :set_orderlist, only: %i[ show edit update destroy ]
  before_action :set_pizzas, only: %i[ new edit create updated]

  # GET /orderlists or /orderlists.json
  def index
    @orderlists = Orderlist.all
  end

  # GET /orderlists/1 or /orderlists/1.json
  def show
  end

  # GET /orderlists/new
  def new
    @orderlist = Orderlist.new
    @order = Order.find(params[:order_id])
  end

  # GET /orderlists/1/edit
  def edit
  end

  # POST /orderlists or /orderlists.json
  def create
    @order = Order.find(params[:order_id])
    @orderlist = @order.orderlists.new(params[:pizza], params[:size])
    # @orderlist = @order
    respond_to do |format|
      if @orderlist.save
        format.html { redirect_to order_path(@order), notice: "Orderlist was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @orderlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderlists/1 or /orderlists/1.json
  def update
    respond_to do |format|
      if @orderlist.update(orderlist_params)
        format.html { redirect_to orderlist_url(@orderlist), notice: "Orderlist was successfully updated." }
        format.json { render :show, status: :ok, location: @orderlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @orderlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderlists/1 or /orderlists/1.json
  def destroy
    @orderlist.destroy

    respond_to do |format|
      format.html { redirect_to orderlists_url, notice: "Orderlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderlist
      @orderlist = Orderlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orderlist_params
      # params.require(:orderlist).permit!()
    end

    def set_pizzas
      @pizzas = Pizza.all      
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def index
	 	@orders = Order.all
	end
	def new
		@order = Order.create!
		redirect_to order_path(@order)
	end
	
	def show
		@order = Order.find(params[:id])
	end
	
	def complete_order
    	@order = Order.find(params[:order_id])
    	if @order.update(completed: true)
    		redirect_to order_path(@order), notice: "Order was successfully updated."
    	end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orderlists_helper.rb
module OrderlistsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/home/index.html.erb
<%= link_to 'Orders', orders_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaOrderOm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orderlists/_form.html.erb
<div class="container">
  <%= form_with(url: [@order , orderlist]) do |form| %>
    <% if orderlist.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(orderlist.errors.count, "error") %> prohibited this orderlist from being saved:</h2>
        <ul>
          <% orderlist.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
        <% options = options_from_collection_for_select(@pizzas, 'id', 'name') %>
        <%= form.select :pizza,  options %>
    </div>
    <div>
      <%= form.label :size%>
      <%= form.select :size, ['Small', 'medium', 'large']%>    

    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/orderlists/_orderlist.html.erb
<div id="<%= dom_id orderlist %>">
	
</div>

app/views/orderlists/edit.html.erb
<h1>Editing orderlist</h1>

<%= render "form", orderlist: @orderlist %>

<br>

<div>
  <%= link_to "Show this orderlist", @orderlist %> |
  <%= link_to "Back to orderlists", orderlists_path %>
</div>

app/views/orderlists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orderlists</h1>

<div id="orderlists">
  <% @orderlists.each do |orderlist| %>
    <%= render orderlist %>
    <p>
      <%= link_to "Show this orderlist", orderlist %>
    </p>
  <% end %>
</div>

<%# link_to "New orderlist", new_orderlist_path %>

app/views/orderlists/new.html.erb
<h1>New orderlist</h1>

<%= render "form", orderlist: @orderlist %>

<br>

<div>
  <!-- <%# link_to "Back to orderlists", orderlists_path %>  to do-->
</div>

app/views/orderlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @orderlist %>

<div>
  <%= link_to "Edit this orderlist", edit_orderlist_path(@orderlist) %> |
  <%= link_to "Back to orderlists", orderlists_path %>

  <%= button_to "Destroy this orderlist", @orderlist, method: :delete %>
</div>

app/views/orders/index.html.erb
<div class='container mt-5'>
	<%= link_to "New Order", new_order_path%>
	<% @orders.each do |order|%>
		<div class = 'row'>
			<div class="col-6">
				ID: <%=order.id%><br/>
				Created: <%= order.created_at%><br/>
				Promotion Code: <%= order.promotion_code%><br/>
			</div>
			<div class="col-6">
				Items:
				<ul>
					<%order.orderlists.each do |orderlist| %>
						<li> <%= orderlist.pizza.name %>(<%= orderlist.size %>)</li>	
					<% end %>
				</ul>
			</div>
		</div>
		<div class="mt-4">
			<% if order.completed? %>
				<p>Order is completed</p>
			<% else %>
				<%= button_to 'Complete', order_complete_order_path(order), method: :patch%>
			<% end%>
		</div>
		<hr/>
	<% end %>
</div>

app/views/orders/show.html.erb
<div class="container mt-5">
	<%= link_to "Add Item", new_order_orderlist_path(@order)%>
	<div class = 'row'>
		<div class="col-6">
			ID: <%=@order.id%><br/>
			Created: <%= @order.created_at%><br/>
			Promotion Code: <%= @order.promotion_code%><br/>
		</div>
		<div class="col-6">
			Items:
			<ul>
				<%@order.orderlists.each do |orderlist| %>
					<li> <%= orderlist.pizza.name %>(<%= orderlist.size %>)</li>	
				<% end %>
			</ul>
		</div>
		<div class="mt-4">
			<% if @order.completed? %>
				<p>Order is completed</p>
			<% else %>
				<%= button_to 'Complete', order_complete_order_path(@order), method: :patch%>
			<% end%>
		</div>
	</div>
</div>